---
- name: Create the env directory
  ansible.builtin.file:
    dest: "{{ app.prefix.config }}/env"
    state: directory
    owner: proserver
    group: proserver
    mode: "0700"

- name: Template .env file
  ansible.builtin.copy:
    content: "{{ app.config | to_env }}"
    dest: "{{ app.prefix.config }}/env/app.env"
    owner: proserver
    group: proserver
    mode: "0400"

- name: Create webspace directory
  ansible.builtin.file:
    path: "/var/www"
    state: directory
    owner: proserver
    group: proserver
    mode: "0755"
  register: create_webspace_directory
