---
pages:
  tags:
    - docker
  stage: deploy
  script:
    - "cd files"
    - "find -print > ./tree"
    - "cd ../"
    - "mv files public"
  artifacts:
    paths:
      - public
  only:
    - main
