#!/usr/bin/env python3
import os
import difflib
import requests
from pathlib import Path

project = os.path.basename(os.getcwd()).replace("-infrastructure", "")

templates_url = "https://pt.punkt.io/ansible-init.punkt.app/"

def diff(string_list, index_a=0, index_b=None, print_only=True):
    """
    Print or return a colour-coded diff of two items in a list of strings.
    Default: Compare first and last strings; print the output; return None.
    """
    index_b = index_b or len(string_list) -1
    green = '\x1b[38;5;16;48;5;2m'
    red = '\x1b[38;5;16;48;5;1m'
    end = '\x1b[0m'
    output = []
    string_a = string_list[index_a]
    string_b = string_list[index_b]
    matcher = difflib.SequenceMatcher(None, string_a, string_b)
    for opcode, a0, a1, b0, b1 in matcher.get_opcodes():
        if opcode == "equal":
            output += [string_a[a0:a1]]
        elif opcode == "insert":
            output += [green + string_b[b0:b1] + end]
        elif opcode == "delete":
            output += [red + string_a[a0:a1] + end]
        elif opcode == "replace":
            output += [green + string_b[b0:b1] + end]
            output += [red + string_a[a0:a1] + end]
    output = "".join(output)
    if not print_only:
        return output
    print(f"\n{output}\n")

def write_config(filepath):
    reference = requests.get(templates_url + filepath).text
    contents = reference.format(project, os.path.basename(os.getcwd()), os.getcwd())
    fullpath = os.path.join(os.getcwd(), filepath)
    if os.path.isfile(fullpath):
        with open(fullpath, "r+") as targetfile:
            fcontents = targetfile.read()
        if fcontents != contents:
            diff([fcontents, contents])
            replace = None
            print("Replace the file {}? (y/n/a)".format(fullpath))
            while replace not in ("y", "n", "a"):
                if replace == "a":
                    with open(fullpath, "w") as targetfile:
                        targetfile.write(contents)
                    break
                else:
                    replace = input()
                if replace == "y":
                    with open(fullpath, "w") as targetfile:
                        targetfile.write(contents)
                elif replace == "n":
                    exit(0)
                else:
                    print("Please type either 'y' or 'n'")
    else:
        with open(fullpath, "w") as targetfile:
            targetfile.write(contents)


for i in ["roles", "group_vars"]:
    Path(os.path.join(os.getcwd(), i)).mkdir(parents=True, exist_ok=True)
    
write_config(".envrc")
write_config("inventory.py")
write_config("requirements.yml")
write_config("requirements.txt")
write_config(".ansible-lint")
write_config("ansible.cfg")
write_config(".yamllint")
write_config(".pre-commit-config.yaml")
write_config(".gitignore")
write_config(".gitattributes")
write_config("vault_password_file")

os.system('direnv allow')
os.system("git switch --create main")
os.system('pre-commit install')
