---
- name: Template nginx configuration
  ansible.builtin.template:
    src: nginx/http.d/app.conf.j2
    dest: "{{ nginx.prefix.config }}/http.d/app.conf"
    owner: root
    mode: "0644"
  notify: Restart nginx
