---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible
    <<: &default_platform
      command: /lib/systemd/systemd
      pre_build_image: true
      privileged: true
      cgroupns_mode: host
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: ubuntu-2404
    image: geerlingguy/docker-ubuntu2404-ansible
    <<: *default_platform
  - name: debian-12
    image: geerlingguy/docker-debian12-ansible
    <<: *default_platform
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
